---

- name: set GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="{{ grub_cmdline_linux_default }}"'
    backup: yes
    create: no
    backrefs: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Update grub
  command: update-grub
  changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
